$(function(){
    $('.btn-forgot').click(function(){
        $('.forgot').css({
            visibility:'visible'
        });
    });
    $('.forgot').mouseenter(function(){
        $('.forgot').css({
            visibility:'visible'
        });
    });
    $('.forgot').mouseleave(function(){
        $('.forgot').css({
            visibility:'hidden'
        });
    });
    $('.forms-login-by button[type="button"]').click(function(){
        $('.login-by').css({
            visibility:'hidden'
        });
    });
    $('.li-login-by').click(function(){
        $('.login-by').css({
            visibility:'visible'
        });
    });
    $('.forms-tell-superadmin button[type="button"]').click(function(){
        $('.tell-superadmin').css({
            visibility:'hidden'
        });
    });
    $('.li-tell-sa').click(function(){
        $('.tell-superadmin').css({
            visibility:'visible'
        });
    });
    $('.li-menu-satu').click(function(){
        $('.menu-satu').css({
            display:'block'
        });
        $('.menu-dua').css({
            display:'none'
        });
        $('.menu-tiga').css({
            display:'none'
        });
        $('.menu-empat').css({
            display:'none'
        });
        $('.menu-lima').css({
            display:'none'
        });
    });
    $('.li-menu-dua').click(function(){
        $('.menu-satu').css({
            display:'none'
        });
        $('.menu-dua').css({
            display:'block'
        });
        $('.menu-tiga').css({
            display:'none'
        });
        $('.menu-empat').css({
            display:'none'
        });
        $('.menu-lima').css({
            display:'none'
        }); 
    });
    $('.li-menu-tiga').click(function(){
        $('.menu-satu').css({
            display:'none'
        });
        $('.menu-dua').css({
            display:'none'
        });
        $('.menu-tiga').css({
            display:'block'
        });
        $('.menu-empat').css({
            display:'none'
        });
        $('.menu-lima').css({
            display:'none'
        }); 
    });
    $('.li-menu-empat').click(function(){
        $('.menu-satu').css({
            display:'none'
        });
        $('.menu-dua').css({
            display:'none'
        });
        $('.menu-tiga').css({
            display:'none'
        });
        $('.menu-empat').css({
            display:'block'
        });
        $('.menu-lima').css({
            display:'none'
        }); 
    });
    $('.li-menu-lima').click(function(){
        $('.menu-satu').css({
            display:'none'
        });
        $('.menu-dua').css({
            display:'none'
        });
        $('.menu-tiga').css({
            display:'none'
        });
        $('.menu-empat').css({
            display:'none'
        });
        $('.menu-lima').css({
            display:'block'
        }); 
    });
    $('.li-tell-reg').click(function(){
        $('.admin-register').css({
            visibility:'visible'
        });
    });
});