var i=1;
function muncul(){
    if(i==1){
        document.getElementById('bawah-subheader').style.visibility="visible";
            document.getElementById('sb').style.boxShadow="0px 0px 0px 0px";
        i=2;
    }else{
        document.getElementById('bawah-subheader').style.visibility="hidden";
        document.getElementById('sb').style.boxShadow="0px 0px 5px 0px #004fa7";
        i=1;
    }
}
$(function(){
    $(window).scroll(function(){
        if($(window).scrollTop()>100){
            $('.subheader').slideDown('slow');
            $('.top').fadeIn('slow');
            $('.right-side').fadeIn('slow');
        }else{
            $('.subheader').slideUp('slow');
            $('.top').fadeOut('slow');
            $('.right-side').fadeOut('slow');
        }
    });
    $('.top').click(function(){
            $('body,html').animate({
                scrollTop:0
            },1000);
            return false;
        });
    $('.li-kat-tshirt').click(function(){
        $('body,html').animate({
            scrollTop:270
        },1000);
        return false;
    });
    $('.li-kat-dress').click(function(){
        $('body,html').animate({
            scrollTop:590
        },1000);
        return false;
    });
    $('.li-kat-rok').click(function(){
        $('body,html').animate({
            scrollTop:910
        },1000);
        return false;
    });
    $('.li-kat-jeans').click(function(){
        $('body,html').animate({
            scrollTop:1230
        },1000);
        return false;
    });
    $('.li-kat-baby').click(function(){
        $('body,html').animate({
            scrollTop:1550
        },1000);
        return false;
    });
    $('.li-kat-muslim').click(function(){
        $('body,html').animate({
            scrollTop:1870
        },1000);
        return false;
    });
    $('.li-kat-kemeja').click(function(){
        $('body,html').animate({
            scrollTop:2190
        },1000);
        return false;
    });
    $('.li-kat-blezer').click(function(){
        $('body,html').animate({
            scrollTop:2510
        },1000);
        return false;
    });
});
$(function(){
    $(window).scroll(function(){
        if($(window).scrollTop()<=560){
            $('.li-kat-tshirt').css({
                background:'black',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()<=880){
            $('.li-kat-dress').css({
                background:'black',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()<=1200){
            $('.li-kat-rok').css({
                background:'black',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()<=1520){
            $('.li-kat-jeans').css({
                background:'black',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()<=1840){
            $('.li-kat-baby').css({
                background:'black',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()<=2160){
            $('.li-kat-muslim').css({
                background:'black',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()<=2480){
            $('.li-kat-kemeja').css({
                background:'black',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()<=2780){
            $('.li-kat-blezer').css({
                background:'black',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
        }
        else if($(window).scrollTop()>=2800){
            $('.li-kat-blezer').css({
                background:'#004fa7',
            });
            $('.li-kat-tshirt').css({
                background:'#004fa7',
            });
            $('.li-kat-dress').css({
                background:'#004fa7',
            });
            $('.li-kat-jeans').css({
                background:'#004fa7',
            });
            $('.li-kat-baby').css({
                background:'#004fa7',
            });
            $('.li-kat-rok').css({
                background:'#004fa7',
            });
            $('.li-kat-muslim').css({
                background:'#004fa7',
            });
            $('.li-kat-kemeja').css({
                background:'#004fa7',
            });
        }
    });
});
$(function(){
    $('.li-login').click(function(){
       $('.login').slideDown();
        $('.registrasi').slideUp();
        $('.bantuan').slideUp();
    });
    $('.login').mouseenter(function(){
        $('.login').css({
            display:'block',
        });
    });
    $('.login').mouseleave(function(){
        $('.login').slideUp();
    });
    
    $('.download').mouseenter(function(){
        $('.download').css({
            display:'block',
        });
    });
    $('.download').mouseleave(function(){
        $('.download').slideUp();
    });
    $('.li-registrasi').click(function(){
        $('.registrasi').slideDown();
        $('.login').slideUp();
        $('.bantuan').slideUp();
    });
    $('.registrasi').mouseenter(function(){
        $('.registrasi').css({
            display:'block',
        });
    });
    $('.registrasi').mouseleave(function(){
        $('.registrasi').slideUp();
    });
    $('.regist-pembeli').click(function(){
        $('.regis-pembeli').css({
            display:'block'
        });
    });
    $('.regist-penjual').click(function(){
        $('.regis-penjual').css({
            display:'block'
        });
    });
    $('.signin-pembeli').click(function(){
        $('.login-pembeli').css({
            display:'block'
        });
    });
    $('.signin-penjual').click(function(){
        $('.login-penjual').css({
            display:'block'
        });
    });
     $('.ketentuan-seller').click(function(){
        $('.ketentuan-penjual').slideDown();
        $('.kebijakan-penjual').slideUp();
    });
    $('.kebijakan-seller').click(function(){
        $('.ketentuan-penjual').slideUp();
        $('.kebijakan-penjual').slideDown();
    });
    $('.ketentuan-buyer').click(function(){
        $('.ketentuan-pembeli').slideDown();
        $('.kebijakan-pembeli').slideUp();
    });
    $('.kebijakan-buyer').click(function(){
        $('.ketentuan-pembeli').slideUp();
        $('.kebijakan-pembeli').slideDown();
    });
    $('.li-bantuan').click(function(){
        $('.registrasi').slideUp();
        $('.login').slideUp();
        $('.bantuan').slideDown();
    });
    $('.bantuan').mouseleave(function(){
        $('.bantuan').slideUp();
    });
    $('.bantuan').mouseenter(function(){
        $('.bantuan').css({
            display:'block',
        });
    });
});